### PR TITLE
calvin is no good

### PR DESCRIPTION
**Pull request by faiq**
this is a very important change regarding the scoring defaults in mechashy
changes
- calvin has -∞ points

### CODE REVIEW

**Comment by shrugs** [comment]
LGTM :+1:

**Comment by shrugs** [comment]
@Shy this is a hotfix, and is hella necessary

**Comment by shrugs** [comment]
I don't see any tests, actually, so this is unmergeable.

**Comment by nlaz** [comment]
Please comment changelog.

**Comment by faiq** [comment]
@nlaz i updated the comment on the PR accordingly

**Comment by faiq** [comment]
its v important we get this merged

**Comment by bsiddiqui** [comment]
@faiq should check email bc he can change name

**Comment by thecalvinchan** [comment]
Feature Request: Should use "-Infinity" instead of "-∞" for full-fledged ECMA-script support

**Comment by faiq** [comment]
@Shy can we get some input????????????

**Comment by tnip** [comment]
LGTM, Approval

**Comment by Shy** [comment]
Nope.

**Pull request closed without merging**
